# Generated by Django 4.2.10 on 2026-02-10 18:53

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('business_name', models.CharField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+63 912 123 1234'", regex='^\\+63\\s\\d{3}\\s\\d{3}\\s\\d{4}$')])),
                ('business_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('business_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('business_registration', models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('REGISTERED_NON_VAT', 'Registered (NON-VAT)'), ('REGISTERED_VAT', 'Registered (VAT Included)')], default='UNREGISTERED', max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('selfie_with_id', models.FileField(blank=True, null=True, upload_to='merchants/documents/selfies/')),
                ('valid_id', models.FileField(blank=True, null=True, upload_to='merchants/documents/ids/')),
                ('barangay_permit', models.FileField(blank=True, null=True, upload_to='merchants/documents/permits/')),
                ('dti_sec_certificate', models.FileField(blank=True, null=True, upload_to='merchants/documents/certificates/')),
                ('bir_certificate', models.FileField(blank=True, null=True, upload_to='merchants/documents/bir/')),
                ('mayors_permit', models.FileField(blank=True, null=True, upload_to='merchants/documents/mayors/')),
                ('other_documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('temp_registration_data', models.JSONField(blank=True, default=dict)),
                ('registration_step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this merchant belongs to.', related_name='merchant_set', related_query_name='merchant', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this merchant.', related_name='merchant_set', related_query_name='merchant', to='auth.permission', verbose_name='user permissions')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='merchants_email_fc58cd_idx'), models.Index(fields=['username'], name='merchants_usernam_4e9188_idx'), models.Index(fields=['phone_number'], name='merchants_phone_n_8ca20a_idx'), models.Index(fields=['business_name'], name='merchants_busines_c6cdd8_idx'), models.Index(fields=['status'], name='merchants_status_c90f29_idx'), models.Index(fields=['created_at'], name='merchants_created_f43d1d_idx')],
            },
        ),
    ]
