# Generated by Django 4.2.10 on 2026-02-15 21:34

import apps.merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='barangay_permit',
            field=models.FileField(blank=True, null=True, upload_to=apps.merchants.models.barangay_permit_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='bir_certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.merchants.models.bir_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='dti_sec_certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.merchants.models.dti_sec_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='mayors_permit',
            field=models.FileField(blank=True, null=True, upload_to=apps.merchants.models.mayors_permit_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='selfie_with_id',
            field=models.FileField(blank=True, null=True, upload_to=apps.merchants.models.selfie_with_id_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='valid_id',
            field=models.FileField(blank=True, null=True, upload_to=apps.merchants.models.valid_id_upload_path),
        ),
    ]
